{% set name = "oauthenticator" %}
{% set version = "15.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1d9873c9b66e1af973291968b9573d25378bd8c647f30d73b8d8fb27b1a0b85

build:
  number: 0
  # The package ruamel and ruamel.yaml currently are missing on s390x 
  skip: True  # [py<36 or s390x]
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - jsonschema
    - jupyterhub >=1.2
    - requests
    - ruamel.yaml

test:
  imports:
    - oauthenticator
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyterhub/oauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/jupyterhub/oauthenticator/blob/main/LICENSE
  summary: OAuth + JupyterHub Authenticator = OAuthenticator

  doc_url: https://jhubdocs.readthedocs.io/en/latest/oauthenticator/
  dev_url: https://github.com/jupyterhub/oauthenticator
  doc_source_url: https://github.com/jupyterhub/oauthenticator/tree/main/docs/source

extra:
  recipe-maintainers:
    - ericcina
    - sodre
    - consideRatio
