travis:
  secure:
    BINSTAR_TOKEN: mIyaqALctprj+TTi4lVwZ8NrJN0OaLTFDBxYkXh1csuf8qecNliGmlIPrAojWrWb9BvN3v8PtiqR/tmnkbEN75v6r3KM8KDe3X9D5ji7FGv43cHJI8WWjurJKzFLiu25/5pE8gtxwLW45m/Nx5SXW4i3ayyudnasTYwXtukY2LUwxT8oSvlx6sheznMo03n8wwMJyUKNkFWEqiNAdHbt0QXq9HbsVl6Pduy3s60M18GodOOdhTUk0QvBy1vPwElKbzJ2SLO2r0k5QjVLUuLFk9/gKg5xgke+61z/g5XzoNS8lr156AIvugwjmk8tainK4ZhZtFg/DRadzHTy0Vwy+0BD0B7NUoE6MwmOaLgoIKL9hahpoI1aQIQale2kAO2iEwJNrcM/++65VlZTbbAisiv33GTiyTjKRUN1sHYwpfLWvlaxutQie2QY6vpBnoCpn3ximo8+w8v8kFH8mcEYK8M3GA6MFqNryDjqgWV9zl8xfnThuyNQHQEg9pPgcwCmsLzIJPnTGr6WDTUq3APp8Dhvv6TGac6ne1jGwrNAa2QMGLnvVkaKBGuRUNZpfoQmU3+pv7LvnEAb7b/DSP5aWL9rIMRw37++2zXWSez1p47z8JmS2nP/qgaPTYy5gKcecGRx1sg8oPCdRyR1w2RTYNn+qDPqgedcwaosdlCTTjI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
